---
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

<style>
body {
  padding-top:0px
}
.navbar{
  visibility: hidden
}
</style>

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(flexdashboard, DT, dplyr, tidyr)

nwr18 <- readRDS("./output/nwr18_stats.rds")
nfh18 <- readRDS("./output/nfh18_stats.rds")

all_recs <- bind_rows(nwr18, nfh18) %>%
  mutate(orgname = itistools::Cap(orgname),
         orgname = gsub("National Wildlife Refuge", "NWR", orgname),
         orgname = gsub("National Fish Hatchery", "NFH", orgname),
         orgname = gsub(" And Conservation Area", "/CA", orgname),
         orgname = gsub("D'arbonne", "D'Arbonne", orgname))
spp_recs <- all_recs %>%
  filter(itis_taxon_rank %in% c("Genus", "Species", "Subspecies", "Variety"),
         grade == "research")

start_date <- "2018-06-01"

contest_recs <- all_recs %>%
  filter(date >= as.Date(start_date))

contest_recs_spp <- contest_recs %>%
  filter(itis_taxon_rank %in% c("Genus", "Species", "Subspecies", "Variety"),
         grade == "research")

ndays <- as.integer(difftime(as.Date("2018-12-01"), Sys.Date(), units = "days"))
```

Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Leaderboards last updated

```{r}
valueBox(value = format(Sys.time(), '%d %B, %Y'), icon = "glyphicon-calendar")
```

### Unique taxa documented

```{r}
valueBox(n_distinct(contest_recs_spp$sci_name), icon = "glyphicon-camera")
```

### Unique contributors

```{r}
valueBox(value = n_distinct(contest_recs$user), icon = "glyphicon-user")
```

### Refuges/Hatcheries with entries

```{r}
valueBox(n_distinct(contest_recs$orgname), icon = "glyphicon-leaf")
```

### BioBlitz days remaining

```{r}
valueBox(value = ndays, icon = "glyphicon-time")
```

Row
-----------------------------------------------------------------------

### **MOST SPECIES** {data-width=333}

```{r}
most_spp <- spp_recs %>%
  filter(date >= as.Date(start_date)) %>%
  group_by(orgname) %>%
  summarize(n_spp = n_distinct(sci_name)) %>%
  mutate(rank = rank(-1 * n_spp, ties = "min")) %>%
  select(rank, orgname, n_spp) %>%
  arrange(rank, orgname)
names(most_spp) <- c("Rank", "Refuge or Hatchery", "# Total Species")

DT::datatable(most_spp, rownames = FALSE, options = list(
  pageLength = 15,
  columnDefs = list(list(width = '20px', targets = 0),
                    list(width = '60px', targets = 2),
                    list(className = 'dt-left', targets = 1))))
```

### **MOST NEW SPECIES** {data-width=333}

```{r}
# Most new species
spp_before <- spp_recs %>%
  filter(date < as.Date(start_date)) %>%
  group_by(orgname) %>%
  summarize(before_spp = n_distinct(sci_name))

spp_after <-  spp_recs %>%
  group_by(orgname) %>%
  summarize(after_spp = n_distinct(sci_name))

most_new <- left_join(spp_after, spp_before, by = "orgname") %>%
  mutate(before_spp = ifelse(is.na(before_spp), 0, before_spp),
         n_new_spp = after_spp - before_spp,
         rank = rank(-1 * n_new_spp, ties = "min")) %>%
  select(rank, orgname, n_new_spp) %>%
  filter(n_new_spp > 0) %>%
  arrange(rank, orgname)
names(most_new) <- c("Rank", "Refuge or Hatchery", "# New Species")

DT::datatable(most_new,  rownames = FALSE, options = list(
  pageLength = 15,
  columnDefs = list(list(width = '20px', targets = 0),
                    list(width = '60px', targets = 2),
                    list(className = 'dt-left', targets = 1))))
```

### **MOST UNIQUE CONTRIBUTORS (≥ 5 records)** {data-width=333}

```{r}
most_users <- contest_recs %>%
  group_by(orgname, user) %>%
  summarize(n_recs = n()) %>%
  filter(n_recs >= 5) %>%
  group_by(orgname) %>%
  summarize(n_users = n_distinct(user)) %>%
  mutate(rank = rank(-1 * n_users, ties = "min")) %>%
  select(rank, orgname, n_users) %>%
  arrange(rank, orgname)
names(most_users) <- c("Rank", "Refuge or Hatchery", "# Total Users")

DT::datatable(most_users,  rownames = FALSE, options = list(
  pageLength = 15,
  columnDefs = list(list(width = '20px', targets = 0),
                    list(width = '60px', targets = 2),
                    list(className = 'dt-left', targets = 1))
))
```